### ISSUE TITLE
Version 2.6 broke my website...

### ISSUE THREAD

**Issue by suede** [VortexThemes/rating-system#1]
Hey, I'm using your "was" great wp plugin Rating System, it was so far the best rating plugin in wp store. Until today, I updated the newest 2.6 version, after that I cannot open my website (blank page) anymore, so I have to delete Rating System folder via ftp, to recovery my web alive again.

Hope you guys fix this serious problem asap.

Thx.

**Comment by AlexAlexandru** [comment]
Hello sorry to hear that do you have any error logs or anything?Also with version 2.5 everything was ok?

**Comment by suede** [comment]
2.5 is no problem. I've downloaded the old version from your github replaced new one, everything is fine.  Dunno why, but as I updated 2.6 and reopen plugin, my homepage become blank again. Tomorrow I'll retry to send you the log.

-----原始邮件-----
发件人: "AlexAlexandru" <notifications@github.com>
发送时间: ‎2015/‎10/‎16 22:47
收件人: "VortexThemes/rating-system" <rating-system@noreply.github.com>
抄送: "suede" <auess@163.com>
主题: Re: [rating-system] Version 2.6 broke my website... (#1)

Hello sorry to hear that do you have any error logs or anything?Also with version 2.5 everything was ok?

**Comment by AlexAlexandru** [comment]
Ok thanks waiting for that log

**Comment by AlexAlexandru** [comment]
If you install this version is working?

http://www36.zippyshare.com/v/68zRrIfI/file.html

**Comment by AlexAlexandru** [comment]
Update to 2.7.1 from WordPress

**Comment by suede** [comment]
Hi buddy, 
You fixed my wp problem on rating system 2.7.1, thank u so much. :D


Best regards.




在 2015-10-25 02:44:35，"AlexAlexandru" <notifications@github.com> 写道：


Update to 2.7.1 from WordPress

**Comment by AlexAlexandru** [comment]
Glad to hear that.
